In [132]:
import numpy as np
import pandas as pd

In [133]:
df = pd.read_csv(r"/Users/karanrochlani/Downloads/Detection of Phishing Websites/dataset_website.csv")
df

index  having_IPhaving_IP_Address  URLURL_Length  Shortining_Service  \
0          1                          -1              1                   1   
1          2                           1              1                   1   
2          3                           1              0                   1   
3          4                           1              0                   1   
4          5                           1              0                  -1   
...      ...                         ...            ...                 ...   
11050  11051                           1             -1                   1   
11051  11052                          -1              1                   1   
11052  11053                           1             -1                   1   
11053  11054                          -1             -1                   1   
11054  11055                          -1             -1                   1   

       having_At_Symbol  double_slash_redirecting  Prefix_Suffix  \
0                     1                        -1             -1   
1                     1                         1             -1   
2                     1                         1             -1   
3                     1                         1             -1   
4                     1                         1             -1   
...                 ...                       ...            ...   
11050                -1                         1              1   
11051                -1                        -1             -1   
11052                 1                         1             -1   
11053                 1                         1             -1   
11054                 1                         1             -1   

       having_Sub_Domain  SSLfinal_State  Domain_registeration_length  ...  \
0                     -1              -1                           -1  ...   
1                      0               1                           -1  ...   
2                     -1              -1                           -1  ...   
3                     -1              -1                            1  ...   
4                      1               1                           -1  ...   
...                  ...             ...                          ...  ...   
11050                  1               1                           -1  ...   
11051                  1              -1                           -1  ...   
11052                  1              -1                           -1  ...   
11053                 -1              -1                            1  ...   
11054                 -1              -1                            1  ...   

       popUpWidnow  Iframe  age_of_domain  DNSRecord  web_traffic  Page_Rank  \
0                1       1             -1         -1           -1         -1   
1                1       1             -1         -1            0         -1   
2                1       1              1         -1            1         -1   
3                1       1             -1         -1            1         -1   
4               -1       1             -1         -1            0         -1   
...            ...     ...            ...        ...          ...        ...   
11050           -1      -1              1          1           -1         -1   
11051           -1       1              1          1            1          1   
11052            1       1              1          1            1         -1   
11053           -1       1              1          1            1         -1   
11054            1       1             -1          1           -1         -1   

       Google_Index  Links_pointing_to_page  Statistical_report  Result  
0                 1                       1                  -1      -1  
1                 1                       1                   1      -1  
2                 1                       0                  -1      -1  
3                 1                      -1    

In [134]:
df.isnull().sum()

index                          0
having_IPhaving_IP_Address     0
URLURL_Length                  0
Shortining_Service             0
having_At_Symbol               0
double_slash_redirecting       0
Prefix_Suffix                  0
having_Sub_Domain              0
SSLfinal_State                 0
Domain_registeration_length    0
Favicon                        0
port                           0
HTTPS_token                    0
Request_URL                    0
URL_of_Anchor                  0
Links_in_tags                  0
SFH                            0
Submitting_to_email            0
Abnormal_URL                   0
Redirect                       0
on_mouseover                   0
RightClick                     0
popUpWidnow                    0
Iframe                         0
age_of_domain                  0
DNSRecord                      0
web_traffic                    0
Page_Rank                      0
Google_Index                   0
Links_pointing_to_page         0
Statistica

In [135]:
df.shape

(11055, 32)

In [136]:
df.head()

index  having_IPhaving_IP_Address  URLURL_Length  Shortining_Service  \
0      1                          -1              1                   1   
1      2                           1              1                   1   
2      3                           1              0                   1   
3      4                           1              0                   1   
4      5                           1              0                  -1   

   having_At_Symbol  double_slash_redirecting  Prefix_Suffix  \
0                 1                        -1             -1   
1                 1                         1             -1   
2                 1                         1             -1   
3                 1                         1             -1   
4                 1                         1             -1   

   having_Sub_Domain  SSLfinal_State  Domain_registeration_length  ...  \
0                 -1              -1                           -1  ...   
1                  0               1                           -1  ...   
2                 -1              -1                           -1  ...   
3                 -1              -1                            1  ...   
4                  1               1                           -1  ...   

   popUpWidnow  Iframe  age_of_domain  DNSRecord  web_traffic  Page_Rank  \
0            1       1             -1         -1           -1         -1   
1            1       1             -1         -1            0         -1   
2            1       1              1         -1            1         -1   
3            1       1             -1         -1            1         -1   
4           -1       1             -1         -1            0         -1   

   Google_Index  Links_pointing_to_page  Statistical_report  Result  
0             1                       1                  -1      -1  
1             1                       1                   1      -1  
2             1                       0                  -1      -1  
3             1                      -1                   1      -1  
4             1                       1                   1       1  

[5 rows x 32 columns]

In [137]:
x = df.iloc[:,1:31].values
x

array([[-1,  1,  1, ...,  1,  1, -1],
       [ 1,  1,  1, ...,  1,  1,  1],
       [ 1,  0,  1, ...,  1,  0, -1],
       ...,
       [ 1, -1,  1, ...,  1,  0,  1],
       [-1, -1,  1, ...,  1,  1,  1],
       [-1, -1,  1, ..., -1,  1, -1]])

In [138]:
y = df.iloc[:,-1].values
y

array([-1, -1, -1, ..., -1, -1, -1])

In [139]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=0)

In [140]:
x_train.shape

(8291, 30)

In [141]:
y_train.shape

(8291,)

In [142]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout 

In [143]:
Regression_Model = Sequential()

In [144]:
Regression_Model.add(Dense(units=30, kernel_initializer="random_uniform", activation="relu"))

In [145]:
Regression_Model.add(Dense(units=60, kernel_initializer="random_uniform", activation="relu"))

In [146]:
Regression_Model.add(Dropout(0.2))

In [147]:
Regression_Model.add(Dense(units=60, kernel_initializer="random_uniform", activation="relu"))

In [148]:
Regression_Model.add(Dropout(0.2))

In [149]:
Regression_Model.add(Dense(units=1, kernel_initializer="random_uniform", activation="relu"))

In [150]:
Regression_Model.compile(optimizer = "adam",loss ="mean_squared_error", metrics = ["accuracy"] )

In [151]:
x_train=np.asarray(x_train).astype(np.float32) 
y_train=np.asarray(y_train).astype(np.float32)

In [152]:
history = Regression_Model.fit(x_train,y_train, batch_size =64,epochs = 500)

Epoch 1/500
130/130 [==============================] - 0s 919us/step - loss: 0.6869 - accuracy: 0.3275
Epoch 2/500
130/130 [==============================] - 0s 888us/step - loss: 0.5712 - accuracy: 0.4785
Epoch 3/500
130/130 [==============================] - 0s 885us/step - loss: 0.5622 - accuracy: 0.4934
Epoch 4/500
130/130 [==============================] - 0s 883us/step - loss: 0.5527 - accuracy: 0.4972
Epoch 5/500
130/130 [==============================] - 0s 870us/step - loss: 0.5468 - accuracy: 0.5043
Epoch 6/500
130/130 [==============================] - 0s 864us/step - loss: 0.5426 - accuracy: 0.5055
Epoch 7/500
130/130 [==============================] - 0s 953us/step - loss: 0.5383 - accuracy: 0.5044
Epoch 8/500
130/130 [==============================] - 0s 977us/step - loss: 0.5332 - accuracy: 0.5055
Epoch 9/500
130/130 [==============================] - 0s 971us/step - loss: 0.5292 - accuracy: 0.5078
Epoch 10/500
130/130 [==============================] - 0s 1ms/step - los

130/130 [==============================] - 0s 888us/step - loss: 0.4803 - accuracy: 0.5303
Epoch 80/500
130/130 [==============================] - 0s 846us/step - loss: 0.4772 - accuracy: 0.5315
Epoch 81/500
130/130 [==============================] - 0s 828us/step - loss: 0.4800 - accuracy: 0.5307
Epoch 82/500
130/130 [==============================] - 0s 819us/step - loss: 0.4764 - accuracy: 0.5317
Epoch 83/500
130/130 [==============================] - 0s 829us/step - loss: 0.4776 - accuracy: 0.5313
Epoch 84/500
130/130 [==============================] - 0s 846us/step - loss: 0.4789 - accuracy: 0.5305
Epoch 85/500
130/130 [==============================] - 0s 839us/step - loss: 0.4803 - accuracy: 0.5305
Epoch 86/500
130/130 [==============================] - 0s 830us/step - loss: 0.4784 - accuracy: 0.5301
Epoch 87/500
130/130 [==============================] - 0s 851us/step - loss: 0.4790 - accuracy: 0.5295
Epoch 88/500
130/130 [==============================] - 0s 840us/step - loss:

130/130 [==============================] - 0s 860us/step - loss: 0.4747 - accuracy: 0.5344
Epoch 158/500
130/130 [==============================] - 0s 845us/step - loss: 0.4742 - accuracy: 0.5324
Epoch 159/500
130/130 [==============================] - 0s 843us/step - loss: 0.4731 - accuracy: 0.5355
Epoch 160/500
130/130 [==============================] - 0s 842us/step - loss: 0.4717 - accuracy: 0.5362
Epoch 161/500
130/130 [==============================] - 0s 866us/step - loss: 0.4711 - accuracy: 0.5360
Epoch 162/500
130/130 [==============================] - 0s 840us/step - loss: 0.4702 - accuracy: 0.5360
Epoch 163/500
130/130 [==============================] - 0s 842us/step - loss: 0.4730 - accuracy: 0.5340
Epoch 164/500
130/130 [==============================] - 0s 830us/step - loss: 0.4723 - accuracy: 0.5368
Epoch 165/500
130/130 [==============================] - 0s 835us/step - loss: 0.4731 - accuracy: 0.5346
Epoch 166/500
130/130 [==============================] - 0s 829us/ste

130/130 [==============================] - 0s 857us/step - loss: 0.4695 - accuracy: 0.5360
Epoch 236/500
130/130 [==============================] - 0s 841us/step - loss: 0.4706 - accuracy: 0.5365
Epoch 237/500
130/130 [==============================] - 0s 841us/step - loss: 0.4678 - accuracy: 0.5385
Epoch 238/500
130/130 [==============================] - 0s 863us/step - loss: 0.4683 - accuracy: 0.5370
Epoch 239/500
130/130 [==============================] - 0s 841us/step - loss: 0.4661 - accuracy: 0.5370
Epoch 240/500
130/130 [==============================] - 0s 847us/step - loss: 0.4698 - accuracy: 0.5355
Epoch 241/500
130/130 [==============================] - 0s 840us/step - loss: 0.4729 - accuracy: 0.5353
Epoch 242/500
130/130 [==============================] - 0s 849us/step - loss: 0.4681 - accuracy: 0.5367
Epoch 243/500
130/130 [==============================] - 0s 861us/step - loss: 0.4679 - accuracy: 0.5368
Epoch 244/500
130/130 [==============================] - 0s 842us/ste

130/130 [==============================] - 0s 860us/step - loss: 0.4657 - accuracy: 0.5394
Epoch 314/500
130/130 [==============================] - 0s 837us/step - loss: 0.4687 - accuracy: 0.5366
Epoch 315/500
130/130 [==============================] - 0s 873us/step - loss: 0.4688 - accuracy: 0.5368
Epoch 316/500
130/130 [==============================] - 0s 840us/step - loss: 0.4678 - accuracy: 0.5375
Epoch 317/500
130/130 [==============================] - 0s 857us/step - loss: 0.4665 - accuracy: 0.5390
Epoch 318/500
130/130 [==============================] - 0s 835us/step - loss: 0.4657 - accuracy: 0.5387
Epoch 319/500
130/130 [==============================] - 0s 842us/step - loss: 0.4687 - accuracy: 0.5356
Epoch 320/500
130/130 [==============================] - 0s 846us/step - loss: 0.4674 - accuracy: 0.5371
Epoch 321/500
130/130 [==============================] - 0s 829us/step - loss: 0.4651 - accuracy: 0.5385
Epoch 322/500
130/130 [==============================] - 0s 846us/ste

130/130 [==============================] - 0s 933us/step - loss: 0.4676 - accuracy: 0.5381
Epoch 392/500
130/130 [==============================] - 0s 894us/step - loss: 0.4673 - accuracy: 0.5373
Epoch 393/500
130/130 [==============================] - 0s 897us/step - loss: 0.4666 - accuracy: 0.5375
Epoch 394/500
130/130 [==============================] - 0s 888us/step - loss: 0.4697 - accuracy: 0.5361
Epoch 395/500
130/130 [==============================] - 0s 906us/step - loss: 0.4659 - accuracy: 0.5379
Epoch 396/500
130/130 [==============================] - 0s 891us/step - loss: 0.4687 - accuracy: 0.5367
Epoch 397/500
130/130 [==============================] - 0s 906us/step - loss: 0.4659 - accuracy: 0.5391
Epoch 398/500
130/130 [==============================] - 0s 936us/step - loss: 0.4659 - accuracy: 0.5384
Epoch 399/500
130/130 [==============================] - 0s 904us/step - loss: 0.4689 - accuracy: 0.5344
Epoch 400/500
130/130 [==============================] - 0s 904us/ste

130/130 [==============================] - 0s 1ms/step - loss: 0.4656 - accuracy: 0.5389
Epoch 470/500
130/130 [==============================] - 0s 863us/step - loss: 0.4659 - accuracy: 0.5376
Epoch 471/500
130/130 [==============================] - 0s 865us/step - loss: 0.4656 - accuracy: 0.5370
Epoch 472/500
130/130 [==============================] - 0s 919us/step - loss: 0.4668 - accuracy: 0.5372
Epoch 473/500
130/130 [==============================] - 0s 910us/step - loss: 0.4669 - accuracy: 0.5362
Epoch 474/500
130/130 [==============================] - 0s 902us/step - loss: 0.4664 - accuracy: 0.5379
Epoch 475/500
130/130 [==============================] - 0s 877us/step - loss: 0.4660 - accuracy: 0.5379
Epoch 476/500
130/130 [==============================] - 0s 902us/step - loss: 0.4645 - accuracy: 0.5381
Epoch 477/500
130/130 [==============================] - 0s 917us/step - loss: 0.4645 - accuracy: 0.5384
Epoch 478/500
130/130 [==============================] - 0s 883us/step 

In [153]:
ypred2 = Regression_Model.predict(x_test)

In [154]:
y_pred3=[]
for i in ypred2:
    if i>0:
        y_pred3.append(1)
    else:
        y_pred3.append(-1)

In [155]:
y_pred3

[-1,
 -1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 1,
 1,
 -1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 1,
 -1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 1,
 1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 1,
 1,
 -1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 1,
 -1,
 1,
 -1,


In [156]:
from sklearn.metrics import accuracy_score
log=accuracy_score(y_test,y_pred3)
log

0.9623733719247467

In [157]:
type(Regression_Model)

tensorflow.python.keras.engine.sequential.Sequential

In [158]:
Regression_Model.save('Phishing_Website.h5')

In [162]:
Regression_Model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_18 (Dense)             (None, 30)                930       
_________________________________________________________________
dense_19 (Dense)             (None, 60)                1860      
_________________________________________________________________
dropout_9 (Dropout)          (None, 60)                0         
_________________________________________________________________
dense_20 (Dense)             (None, 60)                3660      
_________________________________________________________________
dropout_10 (Dropout)         (None, 60)                0         
_________________________________________________________________
dense_21 (Dense)             (None, 1)                 61        
Total params: 6,511
Trainable params: 6,511
Non-trainable params: 0
____________________________________________________

In [159]:
from keras.models import load_model
model = load_model('Phishing_Website.h5')

In [160]:
pred=model.predict([[1, 1, 1, 1, 1, -1, 1, -1, -1, -1, -1, 1, -1, 0, 0, -1, -1, -1, 0, -1, -1, 1, -1, -1, -1, -1, 1, -1, -1, -1]])

In [161]:
pred[0]
    

array([0.], dtype=float32)

In [131]:
pred  

array([[0.]], dtype=float32)